services:
  foxxy-mysql:
    container_name: foxxy-mysql
    image: mysql:latest
    ports:
      - "3306"
    volumes:
      - foxxy-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "foxxy-db"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  foxxy-redis:
    container_name: foxxy-redis
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - .docker/volumes/foxxy-redis:/usr/local/etc/redis
      - foxxy-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      timeout: 5s
      retries: 10
    command: ["/usr/local/etc/redis/redis.conf"]
  foxxy-backend:
    container_name: foxxy-backend
    image: foxxy-backend:latest
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      foxxy-mysql:
        condition: service_healthy
      foxxy-redis:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/foxxy-backend/Dockerfile
    tty: yes
volumes:
  foxxy-mysql:
    external: true
  foxxy-redis:
    external: true