services:
  foxxy-mysql:
    container_name: foxxy-mysql
    image: mariadb:latest
    restart: "always"
    expose:
      - "3306"
    networks:
      - foxxy-backend
    volumes:
      - foxxy-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${FOXXY_mysql_PASSWORD}"
      MYSQL_DATABASE: "foxxy-db"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 5s
      retries: 10
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  foxxy-backend:
    container_name: foxxy-backend
    image: foxxy-backend:latest
    restart: "always"
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - foxxy-backend
    volumes:
      - ./configs:/usr/src/app/configs
    environment:
      FOXXY_mysql_PASSWORD: "${FOXXY_mysql_PASSWORD}"
    depends_on:
      foxxy-mysql:
        condition: service_healthy
      foxxy-redis:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/foxxy-backend/Dockerfile
    tty: yes
volumes:
  foxxy-mysql:
    external: true
  foxxy-redis:
    external: true
networks:
  foxxy-backend:
    name: foxxy-backend